name: github-tag-release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use github-tag-release
        id: 'github-tag-release'
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
